export interface User {
  _id: string;
  email: string;
  name: string;
  avatar?: string;
  preferredCurrency: string;
  isEmailVerified: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Place {
  name: string;
  address?: string;
  placeId?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  rating?: number;
  photos?: string[];
  phone?: string;
  website?: string;
  priceLevel?: number;
}

export interface FlightInfo {
  airline: string;
  flightNumber: string;
  departure: {
    airport: string;
    airportCode: string;
    time: string;
    terminal?: string;
    gate?: string;
  };
  arrival: {
    airport: string;
    airportCode: string;
    time: string;
    terminal?: string;
    gate?: string;
  };
  duration?: string; // e.g., "2h 30m"
  aircraft?: string;
  seatNumber?: string;
  bookingReference?: string;
  status?: 'scheduled' | 'delayed' | 'cancelled' | 'boarding' | 'departed' | 'arrived';
}

export interface ItineraryItem {
  id: string;
  _id?: string;
  day: number;
  time: string;
  title: string;
  description?: string;
  location?: {
    name: string;
    address: string;
    coordinates?: {
      lat: number;
      lng: number;
    };
  };
  duration?: number; // in minutes
  type: 'activity' | 'meal' | 'transport' | 'accommodation' | 'flight';
  notes?: string;
  // Flight-specific information
  flightInfo?: FlightInfo;
  // Legacy fields for backward compatibility
  place?: Place;
  date?: string;
  startTime?: string;
  endTime?: string;
  estimatedDuration?: number;
  order?: number;
  isCustom?: boolean;
  customTitle?: string;
  customDescription?: string;
}

export interface BudgetCategory {
  _id?: string;
  name: string;
  budgetAmount: number;
  spentAmount: number;
  color: string;
}

export interface PackingItem {
  _id?: string;
  name: string;
  category: string;
  isPacked: boolean;
  isEssential: boolean;
}

export interface Document {
  _id?: string;
  name: string;
  type: 'passport' | 'visa' | 'ticket' | 'booking' | 'other';
  fileUrl?: string;
  expiryDate?: string;
  notes?: string;
  uploadedAt: string;
}

export interface Collaborator {
  user: User;
  role: 'editor' | 'viewer';
  invitedAt: string;
  acceptedAt?: string;
}

export interface Trip {
  _id: string;
  title: string;
  description?: string;
  destination: string;
  startDate: string;
  endDate: string;
  status: 'planning' | 'ongoing' | 'completed';
  owner: User;
  collaborators: Collaborator[];
  wishlist: Place[];
  itinerary: ItineraryItem[];
  totalBudget: number;
  currency: string;
  budgetCategories: BudgetCategory[];
  packingList: PackingItem[];
  documents: Document[];
  isPublic: boolean;
  shareToken?: string;
  coverImage?: string;
  tags: string[];
  duration: number;
  createdAt: string;
  updatedAt: string;
}

export interface Expense {
  _id: string;
  trip: string;
  user: User;
  amount: number;
  currency: string;
  convertedAmount?: number;
  exchangeRate?: number;
  category: 'food' | 'transport' | 'accommodation' | 'entertainment' | 'shopping' | 'other';
  title: string;
  description?: string;
  location?: string;
  date: string;
  receiptImage?: string;
  tags: string[];
  coordinates?: {
    lat: number;
    lng: number;
  };
  createdAt: string;
  updatedAt: string;
}

export interface Photo {
  url: string;
  caption?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  takenAt?: string;
  uploadedAt: string;
}

export interface JournalEntry {
  _id: string;
  trip: string;
  user: User;
  date: string;
  title?: string;
  content: string;
  photos: Photo[];
  location?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  weather?: {
    temperature: number;
    condition: string;
    icon: string;
  };
  mood?: 'amazing' | 'great' | 'good' | 'okay' | 'disappointing';
  rating?: number;
  tags: string[];
  highlights: string[];
  isPrivate: boolean;
  isAutoGenerated: boolean;
  generatedFrom?: {
    itinerary: boolean;
    expenses: boolean;
    photos: boolean;
  };
  createdAt: string;
  updatedAt: string;
}

export interface ExpenseStats {
  dailySpending: Array<{
    _id: string;
    total: number;
    count: number;
  }>;
  categoryBreakdown: Array<{
    _id: string;
    total: number;
    count: number;
    avgAmount: number;
  }>;
  totalStats: {
    totalSpent: number;
    totalExpenses: number;
    avgExpense: number;
    maxExpense: number;
    minExpense: number;
  };
  budget: {
    total: number;
    remaining: number;
    categories: BudgetCategory[];
  };
  currency: string;
}

export interface Travelogue {
  trip: {
    title: string;
    destination: string;
    startDate: string;
    endDate: string;
    duration: number;
    coverImage?: string;
  };
  summary: {
    totalDays: number;
    totalExpenses: number;
    currency: string;
    expenseBreakdown: Array<{
      _id: string;
      total: number;
      count: number;
    }>;
  };
  dailyEntries: Array<{
    date: string;
    title?: string;
    content: string;
    photos: Photo[];
    location?: string;
    mood?: string;
    rating?: number;
    highlights: string[];
    author: User;
  }>;
  itinerary: ItineraryItem[];
  generatedAt: string;
  generatedBy: User;
}

// API Response types
export interface ApiResponse<T> {
  message: string;
  data?: T;
  error?: string;
}

export interface PaginatedResponse<T> {
  data?: T[];
  trips?: T[]; // For backward compatibility
  totalPages: number;
  currentPage: number;
  total: number;
}

// Form types
export interface LoginForm {
  email: string;
  password: string;
}

export interface RegisterForm {
  name: string;
  email: string;
  password: string;
  confirmPassword: string;
}

export interface TripForm {
  title: string;
  description?: string;
  destination: string;
  startDate: string;
  endDate: string;
  totalBudget?: number;
  currency: string;
  isPublic?: boolean;
  tags?: string;
}

export interface ExpenseForm {
  amount: number;
  currency: string;
  category: string;
  title: string;
  description?: string;
  location?: string;
  date: string;
}

export interface JournalForm {
  date: string;
  title?: string;
  content: string;
  location?: string;
  mood?: string;
  rating?: number;
  tags: string[];
  highlights: string[];
  isPrivate: boolean;
}
