name: Destroy Travel Diary Lambda Infrastructure

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        default: ''

env:
  AWS_REGION: ap-northeast-1
  PROJECT_NAME: travel-diary
  ENVIRONMENT: prod

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        terraform_wrapper: false
    
    - name: Terraform Init
      working-directory: infrastructure-lambda
      run: terraform init
    
    - name: Empty S3 Bucket First
      working-directory: infrastructure-lambda
      run: |
        # Get bucket name and empty it before destruction
        S3_BUCKET=$(terraform output -raw frontend_bucket_name 2>/dev/null || echo "")
        if [ -n "$S3_BUCKET" ]; then
          echo "Emptying S3 bucket: $S3_BUCKET"
          aws s3 rm s3://$S3_BUCKET --recursive || echo "Bucket already empty or doesn't exist"
        fi
    
    - name: Terraform Destroy
      working-directory: infrastructure-lambda
      run: |
        terraform destroy -auto-approve \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="project_name=${{ env.PROJECT_NAME }}" \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="jwt_secret_key=${{ secrets.JWT_SECRET_KEY }}" \
          -var="google_maps_api_key=${{ secrets.GOOGLE_MAPS_API_KEY }}"
    
    - name: Cleanup Summary
      run: |
        echo "🗑️ Lambda infrastructure destroyed successfully!"
        echo "✅ Lambda function deleted"
        echo "✅ API Gateway deleted"
        echo "✅ S3 bucket deleted"
        echo "✅ CloudFront distribution deleted"
        echo "✅ IAM roles deleted"
        echo "ℹ️ DynamoDB tables preserved (shared resource)"
