name: Import Existing AWS Resources

on:
  workflow_dispatch:  # Manual trigger only

env:
  AWS_REGION: ap-northeast-1
  PROJECT_NAME: travel-diary
  ENVIRONMENT: prod

jobs:
  import:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        terraform_wrapper: false
    
    - name: Build Lambda package (required for init)
      run: |
        mkdir -p infrastructure-lambda/lambda-package
        cd python-backend
        pip install -r requirements-lambda.txt -t ../infrastructure-lambda/lambda-package --no-deps
        cp -r . ../infrastructure-lambda/lambda-package/
        cd ../infrastructure-lambda/lambda-package
        zip -r ../backend.zip . -x "tests/*" "*.git*"
        cd ..
        rm -rf lambda-package
    
    - name: Terraform Init
      working-directory: infrastructure-lambda
      run: terraform init
    
    - name: Import Existing Resources
      working-directory: infrastructure-lambda
      run: |
        echo "Importing existing AWS resources..."
        
        # Import IAM Role
        terraform import aws_iam_role.lambda_execution_role travel-diary-prod-lambda-execution-role-v2 || echo "IAM role import failed or doesn't exist"
        
        # Import CloudWatch Log Group
        terraform import aws_cloudwatch_log_group.lambda_logs /aws/lambda/travel-diary-prod-backend-v2 || echo "Log group import failed or doesn't exist"
        
        # Get CloudFront OAC ID and import
        OAC_ID=$(aws cloudfront list-origin-access-controls --query 'OriginAccessControlList.Items[?Name==`travel-diary-prod-s3-oac-v2`].Id' --output text)
        if [ -n "$OAC_ID" ] && [ "$OAC_ID" != "None" ]; then
          terraform import aws_cloudfront_origin_access_control.s3 $OAC_ID || echo "OAC import failed"
        else
          echo "CloudFront OAC not found"
        fi
        
        # Import Lambda function if it exists
        terraform import aws_lambda_function.backend travel-diary-prod-backend-v2 || echo "Lambda function import failed or doesn't exist"
        
        echo "Import process completed"
    
    - name: Terraform Plan After Import
      working-directory: infrastructure-lambda
      run: |
        terraform plan \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="project_name=${{ env.PROJECT_NAME }}" \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="jwt_secret_key=${{ secrets.JWT_SECRET_KEY }}" \
          -var="google_maps_api_key=${{ secrets.GOOGLE_MAPS_API_KEY }}"
